name: Publish to PyPi

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Intalling tools for deployment...
      run: pip install twine wheel
    - name: Building package...
      run: python setup.py sdist bdist_wheel
    - name: Uploading to PyPi...
      env:
        PYPI_USER: ${{ secrets.PYPI_USER }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: twine upload --username $PYPI_USER --password $PYPI_TOKEN dist/*
